### ISSUE TITLE
TypeError: Cannot read property 'hasOwnProperty' of null

### ISSUE THREAD

**Issue by ghost** [BrainJS/brain.js#307]
![A GIF or MEME to give some spice of the internet](https://media.giphy.com/media/3oEjHLHrrN5rtyQEKs/giphy.gif)

## *What* is wrong?

An error occurs on start.
```
/Users/[redcated]/Coding/node_modules/brain.js/dist/utilities/data-formatter.js:45
        if (characters.hasOwnProperty('length')) {
                       ^

TypeError: Cannot read property 'hasOwnProperty' of null
    at DataFormatter.buildCharactersFromIterable (/Users/[redcated]/Coding/node_modules/brain.js/dist/utilities/data-formatter.js:45:24)
    at new DataFormatter (/Users/[redcated]/Coding/node_modules/brain.js/dist/utilities/data-formatter.js:34:10)
    at Function.fromArrayInputOutput (/Users/[redcated]/Coding/node_modules/brain.js/dist/utilities/data-formatter.js:220:27)
    at LSTM.setupData (/Users/[redcated]/Coding/node_modules/brain.js/dist/recurrent/rnn.js:720:54)
    at LSTM.train (/Users/[redcated]/Coding/node_modules/brain.js/dist/recurrent/rnn.js:438:21)
    at Object.<anonymous> (/Users/[redcated]/Coding/src/index.js:5:5)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
```
## *Where* does it happen?

In the trainer.

## *How* do we replicate the issue?

```js
const brain = require('brain.js');

const net = new brain.recurrent.LSTM();

net.train([
  { input: 'All AVRCE schools are closed today due to road conditions', output: true },
  { input: 'Bus drivers are using discretion on side roads today due to road conditions.', output: false },
  { input: 'Bus drivers are using discretion in Kings and Annapolis Counties today due to road conditions.', output: false },
  { input: 'All AVRCE schools closed today due to forecast weather conditions.', output: true },
  { input: 'All AVRCE schools closed today due to road conditions. Offices and worksites opening at 10 am.', output: true },
  { input: 'All AVRCE schools open. Bus drivers will use their discretion on roads today.', output: false },
  { input: 'All AVRCE schools open. Bus drivers will use their discretion on side roads.', output: false },
  { input: 'All AVRCE schools dismissing 3 hours early due to incoming weather/flash freeze conditions.', output: true },
  { input: 'All AVRCE schools open. Bus drivers will use their discretion.', output: false },
  { input: 'All AVRCE schools closed today due to road conditions. Offices/worksites open at 11 am.', output: true },
  { input: 'All AVRCE schools closed today due to present road conditions and incoming weather.', output: true },
  { input: 'All AVRCE schools closed today due to freezing rain. Offices/worksites opening 10 am.', output: true },
  { input: 'All AVRCE schools closed today due to road conditions. Offices/worksites opening 9 am.', output: true },
  { input: 'All West Hants area schools closed today due to road conditions.', output: false },
  { input: 'All AVRCE schools open. Bus drivers will use discretion on side roads in Annapolis & Kings Counties.', output: false },
  { input: 'AVRCE schools in Kings & Annapolis Counties schools closed today. Offices/worksites in Annapolis Co. opening 9 am.', output: true },
  { input: 'All AVRCE schools closed. West Hants offices/worksites closed. Kings & Annapolis offices/worksites opening 9 am.', output: true },
  { input: 'All AVRCE school closed.', output: true },
  { input: 'All AVRCE schools closed today due to weather/road conditions.', output: true },
  { input: 'UPDATE: ALL AVRCE schools closed today due to road conditions. Offices/Worksites open 9 am.', output: true },
  { input: 'Due to road conditions, schools in West Hants & Kings County closed today. Offices/Worksites in West Hants/Kings open 9 am.', output: null },
  { input: 'All AVRCE schools closed today due to road conditions. Offices/worksites open.', output: true },
  { input: 'All AVRCE schools closed today due to road conditions. Offices/worksites opening 9 a.m.', output: true },
  { input: 'All AVRCE schools closed due to weather/road conditions. Offices/worksites opening 9 a.m.', output: true },
  { input: 'Northeast Kings Education Center (NKEC) closed today due to a boiler issue.', output: false },
  { input: 'Bus drivers using their discretion on side roads today.', output: false },
  { input: 'All AVRCE schools will be closed Tues. February 14 due to weather/road conditions. Offices & worksites opening @12 noon', output: true },
  { input: 'All AVRCE schools, offices and worksites will be closed Monday, February 13 due to forecast winter storm.', output: true },
  { input: 'Kings Co. schools closed due to road conditions. Annapolis Co. & West Hants schools open, bus drivers using discretion on side roads.', output: false },
]);

const output = net.run('All AVRCE schools closed today.');

console.log(output); // true
```

## *How* important is this (1-5)?

1

## Expected behavior (i.e. solution)

It should train and output `true` without error.

## Other Comments

**Comment by robertleeplummerjr** [comment]
`  { input: 'Due to road conditions, schools in West Hants & Kings County closed today. Offices/Worksites in West Hants/Kings open 9 am.', output: null },`

Problem is that `null` simply isn't supported.

**Comment by ghost** [comment]
Oh, 🤦‍♂️

**Comment by robertleeplummerjr** [comment]
All good.  Kept me on my toes!
