### ISSUE TITLE
TypeError: value1.concat is not a function with LSTM

### ISSUE THREAD

**Issue by TimmyRB** [BrainJS/brain.js#389]
![Help](https://media1.tenor.com/images/609b729606f6cd62e491088bf6441947/tenor.gif?itemid=5611393)

## *What* is wrong?
When training with LSTM, I get this error
```
TypeError: value1.concat is not a function
    at DataFormatter.toIndexesInputOutput (C:\Users\jnbra\Desktop\ml-testing\node_modules\brain.js\dist\utilities\data-formatter.js:108:40)
    at LSTM.formatDataIn (C:\Users\jnbra\Desktop\ml-testing\node_modules\brain.js\dist\recurrent\rnn.js:836:35)
    at LSTM.setupData (C:\Users\jnbra\Desktop\ml-testing\node_modules\brain.js\dist\recurrent\rnn.js:820:26)
    at LSTM.train (C:\Users\jnbra\Desktop\ml-testing\node_modules\brain.js\dist\recurrent\rnn.js:532:21)
    at stocks.historical.then.response (C:\Users\jnbra\Desktop\ml-testing\stocks.js:40:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

## *Where* does it happen?
In `net.train`

## *How* do we replicate the issue?
My Training Data:
```
const trainData = [
    {
        "input": {
            "date": "2019-03-26"
        },
        "output": {
            "price": "1207.65"
        }
    },
    {
        "input": {
            "date": "2019-03-25"
        },
        "output": {
            "price": "1209.44"
        }
    }
]
```
My Other Code:
```
const brain = require("brain.js");
const net = new brain.recurrent.LSTM();
net.train(trainData, {
        log: true
    })
```
## *How* important is this (1-5)?
5

## Expected behaviour (i.e. solution)
The Net should train with LSTM without this weird issue

## Other Comments
Help would be very much appreciated!

**Comment by mubaidr** [comment]
This input format is not supported. Please check this: https://github.com/BrainJS/brain.js#for-training-with-rnn-lstm-and-gru

That gif though! 😆
