### ISSUE TITLE
npm install failing for me

### ISSUE THREAD

**Issue by jt0dd** [BrainJS/brain.js#390]
## *What* is wrong?
Cant install the project

## *How* do we replicate the issue?
Run npm i on a windows machine I suppose. Not sure if its windows specific but the error logs do say: nsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

## *How* important is this (1-5)?
5

## Expected behavior (i.e. solution)
The components install and I build the project

## Other Comments

```
C:\Users\Jonathan\Documents\GitHub\brain.js>npm i

> deasync@0.1.14 install C:\Users\Jonathan\Documents\GitHub\brain.js\node_modules\deasync
> node ./build.js

`win32-x64-node-10` exists; testing
Binary is fine; exiting

> gl@4.2.2 install C:\Users\Jonathan\Documents\GitHub\brain.js\node_modules\gl
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=10.15.3 runtime=node arch=x64 libc= platform=win32)

C:\Users\Jonathan\Documents\GitHub\brain.js\node_modules\gl>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\Jonathan\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Jonathan\Documents\GitHub\brain.js\node_modules\gl
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gl@4.2.2 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gl@4.2.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by mubaidr** [comment]
Looks like dep. `gl` is failing to install. 

But why is this required in current version of brainjs? @robertplummer I thought  gpujs will only be required in next version.

**Comment by mubaidr** [comment]
Closed by mistake.

**Comment by mubaidr** [comment]
`Brain.js` now depends on a native module to achieve GPU acceleration, which needs build setup for successful install. We have plan to improve documentation to help users install `brain.js` easily. 
You can follow this issue here: https://github.com/BrainJS/brain.js/issues/429
