### ISSUE TITLE
[Help Needed] with "RangeError: Invalid typed array length: 6470995806" error

### ISSUE THREAD

**Issue by LooOOooM** [BrainJS/brain.js#404]
![A GIF or MEME to give some spice of the internet](url)

## *What* is wrong?
I am working on a pattern reconasation program. While using "brain.recurrent.RNN"  with a lot of traindata, about 50000 lines like below, I receive the following error:

```
RangeError: Invalid typed array length: 6470995806
    at typedArrayConstructByLength (<anonymous>)
    at new Float32Array (native)
    at zeros (/home/haxus/my_million_dollars_project/sandbox/newbrain/node_modules/brain.js/dist/utilities/zeros.js:8:10)
    at RandomMatrix.Matrix (/home/haxus/my_million_dollars_project/sandbox/newbrain/node_modules/brain.js/dist/recurrent/matrix/index.js:32:40)
    at new RandomMatrix (/home/haxus/my_million_dollars_project/sandbox/newbrain/node_modules/brain.js/dist/recurrent/matrix/random-matrix.js:33:114)
    at RNN.createInputMatrix (/home/haxus/my_million_dollars_project/sandbox/newbrain/node_modules/brain.js/dist/recurrent/rnn.js:156:26)
    at RNN.mapModel (/home/haxus/my_million_dollars_project/sandbox/newbrain/node_modules/brain.js/dist/recurrent/rnn.js:203:12)
    at RNN.initialize (/home/haxus/my_million_dollars_project/sandbox/newbrain/node_modules/brain.js/dist/recurrent/rnn.js:97:12)
    at RNN.verifyIsInitialized (/home/haxus/my_million_dollars_project/sandbox/newbrain/node_modules/brain.js/dist/recurrent/rnn.js:428:14)
    at RNN.train (/home/haxus/my_million_dollars_project/sandbox/newbrain/node_modules/brain.js/dist/recurrent/rnn.js:535:12)
```

The trainingdata looks like this:
```
[
{ "input": [0.05,1,1,1,1,0,0,0,0,0,0,0,0,1,0,0,1,0.49,0,0,1,0.52,0.43,1,0,0,0,1,0,0.03,0,0,1,0,0,0,0,0,0,0.32,0,1,0,0,0.21,0.48,0,0,0,0,1,1,1,1,1,1,1,0,0,1,0,0,0,1,0,1,0,0.90,0,0,0,0,0,1,1,1,1,1,1,1,0,1,0,1,0.56,0,0,1,0.57,0.54,0.11,0,0,0,0,0,0.58,1,1,0,1,1,0,0,0,0,0.42,0,1,0,1,0.38,0.20,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,1,1,1,1,1,0,1,0.70,0,1,1,1,0,0,1,0,0,0.54,0,0,1,0.57,0.53,0,0,0,1,1,1,1,1,0,0,1,1,0,1,0,0,0.24,0,0,0,0,0.27,0.25,1,0,0,1,1,0,0,0,0,1,0.50,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0], "output": { "A": 1 }},
{ "input": [0,0,0,0,0,0,1,0.66,0,0,0,0,0,1,0,0,0,0.45,0,0,1,0.52,0.43,0,0,0,0,0,1,0,0,1,1,0,0,1,1,0,0,0.38,0,1,0,0,0.31,0.38,0,1,0,0,1,0,0,0,0,1,1,0,0,1,0,0,0,1,0,1,0,0.87,0,0,0,0,0,1,1,1,0,0,0,0,0,1,0,1,0.54,0,0,1,0.57,0.54,0,0,0,0,0,1,0.50,0.99,1,1,1,1,0,0,1,0,0.42,0,1,0,1,0.39,0.20,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,1,1,1,1,1,0,1,0.68,0,1,1,1,0,0,1,0,0,0.53,0,0,0,0.57,0.53,0,0,0,1,1,1,1,1,0,0,1,1,0,1,0,0,0.24,0,0,0,0,0.27,0.26,1,0,0,1,1,0,0,0,0,1,0.50,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0], "output": { "B": 1 }},
{ "input": [0.16,1,1,1,1,0,1,0,0,0,0,0,0,0,0,0,1,0.48,0,0,0,0.49,0.43,1,0,0,1,0,0,0.08,0,0,1,0,0,0,0,0,0,0.30,0,1,0,0,0.23,0.45,0,0,0,0,1,1,1,1,1,1,1,0,0,0,1,0,0,0,1,0,0,0.89,0,0,0,0,0,1,1,1,1,1,1,0,1,1,0,1,0.55,0,0,1,0.57,0.54,0.05,0,0,0,0,0,0.55,1,1,0,1,1,0,0,0,0,0.42,0,1,0,1,0.38,0.20,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,1,1,1,1,0,1,0.69,0,1,1,1,0,0,1,0,0,0.54,0,0,1,0.57,0.53,0,0,0,1,1,1,1,1,0,0,1,1,0,1,0,0,0.24,0,0,0,0,0.27,0.25,1,0,0,1,1,0,0,0,0,1,0.50,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0], "output": { "C": 1 }}
]
```

... 50k more, however that is just the little testset. prod traindata is about 500k - 1M long

## *Where* does it happen?
- brain.recurrent.RNN
- nodejs 8.11.4
- OS Centos 7.x

## *How* do we replicate the issue?
```
const brain = require( "brain.js" );
const data = require('./test_short.json');

const trainingData = data.map(item => ({
        input: item.input,
        output: item.output
}));

const netOptions = {
  hiddenLayers: [30],
  learningRate: 0.001, // global learning rate, useful when training using streams
};

const trainingOptions = {
  //error: 0.001,
  iterations: 1,
  log: details => console.log(details)
};

const network = new brain.recurrent.RNN(netOptions);
const stats = network.train(trainingData, trainingOptions);
console.log(stats);
const net = network.toNeuralNetwork();
const output = net.run([1,1,1,1,1,0,1,0.85,1,1,1,1,0,1,1,0,0,0.62,0,0,1,0.61,0.61,1,0,1,1,0,0,1,1,0,0,1,1,1,1,0,0,0.32,0,1,0,0,0.36,0.38,0,0,0,1,1,1,1,1,1,0,0,0,0,1,0,1,0,1,0,0,1,0.74,1,1,1,1,0,1,0.23,1,1,1,1,0,0,1,0,0,0.57,0,0,1,0.60,0.52,1,0,0,0,1,0,1,1,0,0,1,1,1,1,0,0,0.37,0,1,0,0,0.30,0.30,0,0,1,0,0,1,1,1,1,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,1,1,1,1,1,1,0,0,1,1,1,1,1,0,1,1,0,1,0.62,0,0,1,0.64,0.62,0,0,0,0,0,1,0,0,1,1,0,1,1,0,0,0,0.32,0,1,0,1,0.40,0.08,1,0,0,1,0,1,1,1,1,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,1,1]);
console.log("Prob:", output)

```
## *How* important is this (1-5)?
3

## Expected behavior (i.e. solution)
should work?

## Other Comments
As I am pretty new to brainjs, could anybody lead me to the solution please

**Comment by mubaidr** [comment]
The training data is too much. Split the data into multiple chunks and then train the network. 

This error is being generated by the run-time not the library. 
```cmd
Uncaught RangeError: Invalid typed array length: 6470995806
    at new Float32Array (<anonymous>)
    at <anonymous>:1:1
```

**Comment by LooOOooM** [comment]
Thank for your replay, which pointed me in the right direction.
I finally did a solution with streaming data - -th

**Comment by robertleeplummerjr** [comment]
Fantastic!  Anything possible to share from how you used it?
