### ISSUE TITLE
Cannot create LSTM on 2.0.0-alpha.2

### ISSUE THREAD

**Issue by olirogers** [BrainJS/brain.js#431]
## *What* is wrong?

Using latest version on npm (2.0.0-alpha.2) I get an error when creating a new LTSM net.

For example (from README.md):

```javascript
const brain = require("brain.js");

const net = new brain.recurrent.LSTM();

net.train([
    'doe, a deer, a female deer',
    'ray, a drop of golden sun',
    'me, a name I call myself',
], {
    iterations: 1500,
    errorThresh: 0.011
});

const output = net.run('doe'); // ', a deer, a female deer'
console.log(output);
```

It fails at the `new brain.recurrent.LSTM()` line.

```shell
/Users/orogers/git/auto-code/node_modules/brain.js/src/recurrent/rnn.js:126
    model.outputConnector = new RandomMatrix(
                          ^

TypeError: Cannot set property 'outputConnector' of undefined
    at LSTM.createOutputMatrix (/Users/orogers/git/auto-code/node_modules/brain.js/src/recurrent/rnn.js:126:27)
    at LSTM.mapModel (/Users/orogers/git/auto-code/node_modules/brain.js/src/recurrent/rnn.js:186:10)
    at LSTM.initialize (/Users/orogers/git/auto-code/node_modules/brain.js/src/recurrent/rnn.js:51:12)
    at new RNN (/Users/orogers/git/auto-code/node_modules/brain.js/src/recurrent/rnn.js:29:10)
    at new LSTM (/Users/orogers/git/auto-code/node_modules/brain.js/src/recurrent/lstm.js:5:1)
    at Object.<anonymous> (/Users/orogers/git/auto-code/ml.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:879:10)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
```

## *Where* does it happen?
Creating a `new brain.recurrent.LSTM()`

## *How* do we replicate the issue?
Copy the code above and run on 2.0.0-alpha2

## *How* important is this (1-5)?
5 - Should be able to use simple LSTM nets.

## Expected behavior (i.e. solution)
It should create a new net. This works if I specify the version as `^1` in the package.json.

## Other Comments

**Comment by robertleeplummerjr** [comment]
I'll have this fixed early part of this week.  So sorry for the inconvenience.

**Comment by robertleeplummerjr** [comment]
I believe this to be solved with https://www.npmjs.com/package/brain.js/v/2.0.0-alpha.3, as unit tests for this line now pass.   Going to go ahead and close, please reopen if the issue persists.

**Comment by olirogers** [comment]
I can confirm that this now works with latest NPM version (2.0.0-alpha.5).

Thanks for fixing so quickly and for producing this excellent software!

**Comment by robertleeplummerjr** [comment]
np!
