### ISSUE TITLE
TypeError: Cannot read property 'weights' of undefined

### ISSUE THREAD

**Issue by 8483** [BrainJS/brain.js#509]
**Error:**
```
/node_modules/brain.js/src/recurrent/rnn-time-step.js:279
    const result = [lastOutput.weights[0]];
                               ^

TypeError: Cannot read property 'weights' of undefined
    at LSTMTimeStep.forecastNumbers (/node_modules/brain.js/src/recurrent/rnn-time-step.js:279:32)
    at LSTMTimeStep.runObject (/node_modules/brain.js/src/recurrent/rnn-time-step.js:293:14)
    at LSTMTimeStep.run (/node_modules/brain.js/src/recurrent/rnn-time-step.js:104:21)
    at Object.<anonymous> (/forecast.js:123:17)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
```

**Code:**
```javascript
const brain = require("brain.js");

let data = [
    { sales: 0 },
    { sales: 0 },
    { sales: 0 },
    { sales: 0 },
    { sales: 0 },
    { sales: 0 },
    { sales: 92 },
    { sales: 759 },
    { sales: 3691 },
    { sales: 4039 },
    { sales: 2257 },
    { sales: 1736 },
    { sales: 3979 },
    { sales: 3170 },
    { sales: 6092 },
    { sales: 7839 },
    { sales: 5764 },
    { sales: 5512 },
    { sales: 5494 },
    { sales: 7458 },
    { sales: 3721 },
    { sales: 8512 },
    { sales: 1089 },
    { sales: 7462 },
    { sales: 710 },
    { sales: 4534 },
    { sales: 6224 },
    { sales: 7610 },
    { sales: 3976 },
    { sales: 6243 },
    { sales: 1532 },
    { sales: 2204 },
    { sales: 801 },
    { sales: 1575 },
    { sales: 2144 },
    { sales: 3679 },
    { sales: 217 },
    { sales: 5136 },
    { sales: 3052 },
    { sales: 4320 },
    { sales: 2750 },
    { sales: 2527 },
    { sales: 13962 },
    { sales: 2266 },
    { sales: 741 },
    { sales: 4220 },
    { sales: 3603 },
    { sales: 2688 },
    { sales: 5850 },
    { sales: 3387 },
    { sales: 4692 },
    { sales: 5251 },
    { sales: 9399 },
    { sales: 7165 },
    { sales: 5032 },
    { sales: 4208 },
    { sales: 1342 },
    { sales: 1571 },
    { sales: 1903 },
    { sales: 3614 },
    { sales: 5250 },
    { sales: 1631 },
    { sales: 2189 },
    { sales: 1850 },
    { sales: 2665 },
    { sales: 2645 },
    { sales: 2268 },
    { sales: 3233 },
    { sales: 1335 },
    { sales: 789 },
    { sales: 538 },
    { sales: 572 },
    { sales: 1011 },
    { sales: 6 },
];

let max = Math.max(...data.map(o => o.sales));
let min = Math.min(...data.map(o => o.sales));

function normalize(step) {
    return { sales: (step.sales - min) / (max - min) };
}

function denormalize(step) {
    return { sales: step.sales * (max - min) + min };
}

let scaledData = data.map(normalize)

let trainingData = [
    scaledData.slice(0, 12),
    scaledData.slice(12, 24),
    scaledData.slice(24, 36),
    scaledData.slice(36, 48),
    scaledData.slice(48, 60),
    scaledData.slice(60, 72),
]

console.log(trainingData)

const net = new brain.recurrent.LSTMTimeStep({
    inputSize: 1,
    hiddenLayers: [1], 
    outputSize: 1
});

net.train(trainingData, {
    iterations: 200,
    learningRate: 0.005,
    errorTresh: 0.02,
    log: (stats) => console.log(stats)
})

console.log(net.run(trainingData[0]));
```

**Comment by mubaidr** [comment]
Confirmed!

**Comment by SergioLag** [comment]
Did you finally know why it was?

**Comment by robertleeplummerjr** [comment]
Working example here: https://observablehq.com/@robertleeplummerjr/brain-js-issue-509

Notice that the original data shape was not compatible, and was slightly altered.
