### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by mishagodovanuk** [BrainJS/brain.js#537]
I get error in /home/user/node_extensions/brain.js/src/index line 8  on { FeedForward } brackets.

1) I try install brain.js like npm install or git clone, and it's ok. But when i try to require it in my.js file like `var brain = require('brain.js')` and execute this file `nodejs my.js` i get error 
`/home/countzero/node_modules/brain.js/src/index.js:8
const { FeedForward } = require('./feed-forward');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/countzero/Desktop/nn/nn.js:1:75)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)`.

Brain.js - latest version.
node.js 4.2.6
Firefox 75.0 (64 bit)

**Comment by mubaidr** [comment]
Please follow this template to submit issue: 
[Create New Issue](https://github.com/BrainJS/brain.js/issues/new)

Otherwise we cannot have enough information regarding this error to help you.
