### ISSUE TITLE
Unable to install brain.js on macOS - error gyp ERR! stack Error: `make` failed with exit code: 2

### ISSUE THREAD

**Issue by realrecordzLab** [BrainJS/brain.js#713]
I'm trying to install the library using the command `npm i brain.js` but it will fail. 
into the error log I've found this error 
```
error gyp ERR! stack Error: `make` failed with exit code: 2
``` 

I'm on macOS 10.13.6
node v16.1.0
npm 7.14.0

I' unable to install the library and to use it in my project. Is there any fix?I've seen the readme but it's not clear where the `npm rebuild` command needs to be called.

Is there

**Comment by tupe12334** [comment]
me to

[2021-07-01T14_41_41_808Z-debug.log](https://github.com/BrainJS/brain.js/files/6749005/2021-07-01T14_41_41_808Z-debug.log)

**Comment by ybaidiuk** [comment]
same stuff.

**Comment by dev-fredericfox** [comment]
Same. 

```npm ERR! gyp ERR! stack Error: `make` failed with exit code: 69```

I am using <script> tag as fallback for now.

**Comment by EduApps-CDG** [comment]
Same in Linux

**Comment by thierryntoh24** [comment]
Same here, Win10 Installation Error

```
PS D:\Projects\art-review-bot> npm install brain.js
npm ERR! code 1
npm ERR! path D:\Projects\art-review-bot\node_modules\gl
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c prebuild-install || node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.13.1 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.2 found at "C:\Users\Thierry_Ntoh\AppData\Local\Programs\Python\Python310\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version was set from command line or npm config
npm ERR! gyp ERR! find VS - looking for Visual Studio version 2022
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS unknown version "undefined" found at "C:\Program Files\Microsoft Visual Studio\2022\Community"
npm ERR! gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS valid versions for msvs_version:
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (D:\Projects\art-review-bot\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
npm ERR! gyp ERR! stack     at D:\Projects\art-review-bot\node_modules\node-gyp\lib\find-visualstudio.js:74:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (D:\Projects\art-review-bot\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
npm ERR! gyp ERR! stack     at D:\Projects\art-review-bot\node_modules\node-gyp\lib\find-visualstudio.js:70:14
npm ERR! gyp ERR! stack     at D:\Projects\art-review-bot\node_modules\node-gyp\lib\find-visualstudio.js:372:16
npm ERR! gyp ERR! stack     at D:\Projects\art-review-bot\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at D:\Projects\art-review-bot\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:404:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! System Windows_NT 10.0.18363
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Projects\\art-review-bot\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd D:\Projects\art-review-bot\node_modules\gl
npm ERR! gyp ERR! node -v v16.13.1
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Thierry_Ntoh\AppData\Local\npm-cache\_logs\2022-01-20T01_07_53_900Z-debug.log
```

Even though i have VS 2022 and Python 3.10 installed

**Comment by robertleeplummerjr** [comment]
This is an issue of https://github.com/stackgl/headless-gl, a dependency of GPU.js, which is a peer-dependency of brain.js.  Please use their tutorials for installation, and if issue continue to throw, please resolve with their support.
