### ISSUE TITLE
Getting Unrecognized Data Error with RNN, LSTM, and GRU

### ISSUE THREAD

**Issue by JeffMII** [BrainJS/brain.js#788]
![A GIF or MEME to give some spice of the internet](https://themiawave.org/wp-content/uploads/2020/04/Meme-of-the-Week-4-Apr-16-2020-at-8_40-AM.png)

## _What_ is wrong?

```
%Project_Root%\node_modules\brain.js\dist\index.js:6616
            throw new Error('unrecognized data');
            ^

Error: unrecognized data
    at DataFormatter.format (%Project_Root%\node_modules\brain.js\dist\index.js:6616:19)
    at GRU.train (%Project_Root%\node_modules\brain.js\dist\index.js:7567:49)
    at Object.<anonymous> (%Project_Root%\BrainJS\brain.js:93:20)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

## _Where_ does it happen?

This seems to be occurring when one of the RNN, LSTM, or GRU train() methods are called with an array of IRNNDatum. I'm doing this in Node.js on Windows 11.

## _How_ do we replicate the issue?

```
const brain = require('brain.js')

const trainingData = [

  { input: 'Doug', ouput: 'Jane saw Doug.' },
  { input: 'Jane', output: 'Doug saw Jane.' },
  { input: 'Spot', output: 'Spot saw Doug and Jane looking at each other.' },
  { input: 'It', output: 'It was love at first sight, and Spot had a frontrow seat. It was a very special moment for all.' },

]

const rnn = new brain.recurrent.RNN()
const result = rnn.train(trainingData, { log: true })
console.log('Training result: ', result)

const run1 = rnn.run('Jane')
const run2 = rnn.run('Doug')
const run3 = rnn.run('Spot')
const run4 = rnn.run('It')

console.log('run 1: Jane' + run1)
console.log('run 2: Doug' + run2)
console.log('run 3: Spot' + run3)
console.log('run 4: It' + run4)
```

## Expected behavior (i.e. solution)

console logs of training statuses and run predictions

### Nodejs:

node@17.7.2

### Brain.js:

brain.js@2.0.0-beta.15

## _How_ important is this (1-5)?

Well personally, as a graduate student trying to use this for a research project, a 5.

## Other Comments

Let me know if I'm just doing it wrong. Thanks for the help.

**Comment by JeffMII** [comment]
Oooh I found it. I had a typo in the first output property name of the training data. Also, it looks like I need to use LSTM for string data.
