### ISSUE TITLE
Node-gyp and Visual Studio not found although I have it installed

### ISSUE THREAD

**Issue by EntropicBlackhole** [BrainJS/brain.js#856]
When running `npm install --save brain.js` I get several errors.

Main ones are about Visual Studio not being installed and stack gyp

I have no idea what this could be because I have Visual Studio 2022 installed, and I did activate for creating projects with C++, if anything my Node version is v18.12.1, which is the latest recommended one.

I've been having this issue for months and never decided to really try to investigate further, but I'm finally creating an Issue here.

Here:
```npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\aschr\\Dropbox\\Coding\\Javascript\\artificial intelligence\\node_modules\\through2',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\aschr\Dropbox\Coding\Javascript\artificial intelligence\node_modules\through2\node_modules\readable-stream'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\aschr\\Dropbox\\Coding\\Javascript\\artificial intelligence\\node_modules\\through2\\node_modules\\readable-stream'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\aschr\Dropbox\Coding\Javascript\artificial intelligence\node_modules\gl
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c prebuild-install || node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@18.12.1 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.8 found at "C:\Users\aschr\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS unknown version "undefined" found at "C:\Program Files\Microsoft Visual Studio\2022\Community"
npm ERR! gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\aschr\Dropbox\Coding\Javascript\artificial intelligence\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
npm ERR! gyp ERR! stack     at C:\Users\aschr\Dropbox\Coding\Javascript\artificial intelligence\node_modules\node-gyp\lib\find-visualstudio.js:74:16      
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\aschr\Dropbox\Coding\Javascript\artificial intelligence\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
npm ERR! gyp ERR! stack     at C:\Users\aschr\Dropbox\Coding\Javascript\artificial intelligence\node_modules\node-gyp\lib\find-visualstudio.js:70:14      
npm ERR! gyp ERR! stack     at C:\Users\aschr\Dropbox\Coding\Javascript\artificial intelligence\node_modules\node-gyp\lib\find-visualstudio.js:372:16     
npm ERR! gyp ERR! stack     at C:\Users\aschr\Dropbox\Coding\Javascript\artificial intelligence\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Users\aschr\Dropbox\Coding\Javascript\artificial intelligence\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:420:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! gyp ERR! System Windows_NT 10.0.22623
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\aschr\\Dropbox\\Coding\\Javascript\\artificial intelligence\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\aschr\Dropbox\Coding\Javascript\artificial intelligence\node_modules\gl
npm ERR! gyp ERR! node -v v18.12.1
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aschr\AppData\Local\npm-cache\_logs\2022-11-15T18_28_08_941Z-debug-0.log

**Comment by EntropicBlackhole** [comment]
After doing some searching, I believe this is simply just wrong paths being called, does anyone know how to fix this?

**Comment by TonyIvanova** [comment]
Same issue here.
